title: "Louise Chisholm"
author: "L. Chisholm"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "DRI.md", DRI}
  - {title: Programme Management, https://louisechisholm.github.io/Programme_Management/}
  - {file: "Facilitating_Research.md", Facilitating Research}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:l.chisholm@ucl.ac.uk"}
  - {title: Github, icon: github, url: "https://github.com/LouiseChisholm"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/lou_chisholm"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
